### ISSUE TITLE
'TypeError: BabyBuddySensor.async_add_diaper_change() got an unexpected keyword argument 'type''

### ISSUE THREAD

**Issue by jeroenterheerdt** [OttPeterR/addon-babybuddy#30]
See title - whenever I call the 'Add diaper change' service it returns an 'unknown error' and this is in the logs:

```
TypeError: BabyBuddySensor.async_add_diaper_change() got an unexpected keyword argument 'type'
```

I am on the latest Babybuddy add-on version.

**Comment by jeroenterheerdt** [comment]
was able to resolve this by downgrading the add-on to v2.6.4

**Comment by OttPeterR** [comment]
I don't believe I've messed around with how HA passes parameters to BB service calls, so my gut reaction is to think this is being caused by something else. But fixing the issue by downgrading does make it seem like it's the add-on's fault. I'm running the up-to-date addon and I do not see the issue. Here's an automation I have with that `type` parameter that doesn't error (for me), not sure if it'll be too much helps since its just the basics, but it's what I have working:

```
service: babybuddy.add_diaper_change
target:
  entity_id: sensor.my_baby_1
data:
  type: Solid
  time: "00:00:00"
```
